include_guard()

string(TOUPPER ${PROJECT_NAME} PROJECT_NAME_UPPER)
set(VERSION_MAJOR ${${PROJECT_NAME}_VERSION_MAJOR})
configure_file(${CMAKE_CURRENT_LIST_DIR}/config.h.in include/ctl/config.h @ONLY)

add_library(${PROJECT_NAME}_config INTERFACE
            ${CMAKE_CURRENT_BINARY_DIR}/include/${PROJECT_NAME}/config.h)

target_include_directories(
  ${PROJECT_NAME}_config
  INTERFACE $<BUILD_INTERFACE:${CMAKE_CURRENT_BINARY_DIR}/include>
            $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>)

install(
  TARGETS ${PROJECT_NAME}_config
  EXPORT ${PROJECT_NAME}_targets
  ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
  LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
  RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})

string(TOUPPER ${PROJECT_NAME} PN_UP)
set_property(GLOBAL APPEND PROPERTY ${PN_UP}_COMPONENTS ${PROJECT_NAME}_config)

install(FILES ${CMAKE_CURRENT_BINARY_DIR}/include/${PROJECT_NAME}/config.h
        DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/${PROJECT_NAME})
